### ISSUE TITLE
Scraper fails for autoscale clusters

### ISSUE THREAD

**Issue by kmate** [datapao/dac#10]
In case of autoscaling clusters there's no `num_workers` key in the dictionary. (However there's a key like this `'autoscale': {'min_workers': 1, 'max_workers': 2}`.)
```
  File "dac/scraping/scraper.py", line 72, in scrape_cluster
    num_workers=cluster_dict["num_workers"],
KeyError: 'num_workers'
```

**Comment by fulibacsi** [comment]
Thanks for the feedback, looking into it.

**Comment by fulibacsi** [comment]
Resolved.
