### ISSUE TITLE
Scraper fails for jobs created on existing clusters

### ISSUE THREAD

**Issue by kmate** [datapao/dac#12]
In that case, the `settings` object contains an `existing_cluster_id` key, but not a `new_cluster` key. This is permitted according to the Databricks Job API docs.
```
  File "dac/scraping/scraper.py", line 174, in scrape_jobs
    new_cluster=job_dict["settings"]["new_cluster"],
KeyError: 'new_cluster'
```

**Comment by fulibacsi** [comment]
Thanks for the feedback, looking into it.

**Comment by fulibacsi** [comment]
Resolved.
