### ISSUE TITLE
Scraper fails for job runs without cluster instance

### ISSUE THREAD

**Issue by kmate** [datapao/dac#13]
A key error raises when accessing `job_run_dict['cluster_instance"]`. According to the Databricks Job API docs, this is not always present:

> The cluster used for this run. If the run is specified to use a new cluster, this field will be set once the Jobs service has requested a cluster for the run.

**Comment by fulibacsi** [comment]
Thanks for the feedback, looking into it.

**Comment by fulibacsi** [comment]
Resolved.
