### ISSUE TITLE
Scraper still fails on `result_state` for pending jobs

### ISSUE THREAD

**Issue by kmate** [datapao/dac#18]
```
  File "dac/scraping/scraper.py", line 151, in scrape_job_run
    state_result_state=state["result_state"] if not failed_run else 'FAIL',
KeyError: 'result_state'
```
See the [docs](https://docs.databricks.com/dev-tools/api/latest/jobs.html#runresultstate) on availability of `result_state`, based on the `life_cycle_state`.

**Comment by fulibacsi** [comment]
Thanks for the feedback, we're working on it.

**Comment by fulibacsi** [comment]
Missing states no longer stored. Solution available on master branch.
