### ISSUE TITLE
Possible memory leak in scraper

### ISSUE THREAD

**Issue by kmate** [datapao/dac#24]
We have been already running the DAC for a few days and after around a week the operating system killed the scraper because of reaching memory limits:
```
scripts/dac.sh: line 23:     6 Killed                  python main.py scrape
[Wed Apr  8 02:51:32 2020] Memory cgroup out of memory: Killed process 7871 (python) total-vm:1209768kB, anon-rss:334320kB, file-rss:33360kB, shmem-rss:0kB
```
Could there be a memory leak somewhere? (We didn't really give it too much memory, I know...)

**Comment by fulibacsi** [comment]
Thanks for the feedback, I'll look into the issue.

**Comment by kmate** [comment]
Thank you!
