### ISSUE TITLE
Scraper fails on event type `INIT_SCRIPTS_STARTED`

### ISSUE THREAD

**Issue by kmate** [datapao/dac#9]
The dac-scraper process dies with the following:
```
ValueError: Unkown event: { ..., 'type': 'INIT_SCRIPTS_STARTED', ... }

Recognized events are: ['INIT', 'CREATING', 'DID_NOT_EXPAND_DISK', 'EXPANDED_DISK', 'FAILED_TO_EXPAND_DISK', 'INIT_SCRIPTS_STARTING', 'INIT_SCRIPTS_FINISHED', 'STARTING', 'RESTARTING', 'TERMINATING', 'EDITED', 'RUNNING', 'RESIZING', 'UPSIZE_COMPLETED', 'NODES_LOST', 'DRIVER_HEALTHY', 'DRIVER_UNAVAILABLE', 'SPARK_EXCEPTION', 'DRIVER_NOT_RESPONDING', 'DBFS_DOWN', 'METASTORE_DOWN', 'AUTOSCALING_STATS_REPORT', 'NODE_BLACKLISTED', 'PINNED', 'UNPINNED']
```

**Comment by fulibacsi** [comment]
Thanks for the feedback, looking into it.

**Comment by kmate** [comment]
Note that the [docs](https://databricks.com/blog/2018/08/30/introducing-cluster-scoped-init-scripts.html) are mentioning `INIT_SCRIPTS_STARTING`, but there's a [blog entry](https://databricks.com/blog/2018/08/30/introducing-cluster-scoped-init-scripts.html) that mentions `INIT_SCRIPTS_STARTED`.

**Comment by fulibacsi** [comment]
Thanks for the link to the blog.

**Comment by fulibacsi** [comment]
Resolved.
